# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"color": "01_helper.ipynb",
         "tint": "01_helper.ipynb",
         "tracker": "01_helper.ipynb",
         "emberTracker": "01_helper.ipynb",
         "check_existance": "01_utils.ipynb",
         "HOME": "01_utils.ipynb",
         "EMBER": "01_utils.ipynb",
         "DATA": "01_utils.ipynb",
         "LOG": "01_utils.ipynb",
         "get_ember_list": "01_utils.ipynb",
         "unpack_meta": "01_utils.ipynb",
         "get_ember_df": "01_utils.ipynb",
         "get_ember_record": "01_utils.ipynb",
         "emberReader": "01_utils.ipynb",
         "clean_kv": "01_utils.ipynb",
         "io_cleaner": "01_utils.ipynb",
         "moduleTrack": "10_torch_ember_core.ipynb",
         "get_stats": "10_torch_ember_core.ipynb",
         "torchEmber": "10_torch_ember_core.ipynb",
         "md5hash": "20_why_hat.ipynb",
         "ModelInput": "20_why_hat.ipynb",
         "InputEmb": "20_why_hat.ipynb",
         "InputOneHot": "20_why_hat.ipynb",
         "InputConti": "20_why_hat.ipynb",
         "YEncoder": "20_why_hat.ipynb",
         "YOneHot": "20_why_hat.ipynb",
         "YConti": "20_why_hat.ipynb",
         "RichColumn": "20_why_hat.ipynb",
         "RichDF": "20_why_hat.ipynb",
         "TabularModel": "20_why_hat.ipynb",
         "TabularNN": "20_why_hat.ipynb",
         "EmberCallback": "50_extension_fastai.ipynb",
         "scatter_cols": "60_interact.ipynb",
         "html": "60_interact.ipynb",
         "Visualize": "60_interact.ipynb",
         "VisualByTensor": "60_interact.ipynb",
         "moving_track": "60_interact.ipynb",
         "clean_module_name": "60_interact.ipynb",
         "VisualMovement": "60_interact.ipynb"}

modules = ["helper.py",
           "utils.py",
           "core.py",
           "whyhat.py",
           "fastai.py",
           "visual.py"]

doc_url = "https://raynardj.github.io/torchember/"

git_url = "https://github.com/raynardj/torchember/tree/master/"

def custom_doc_links(name): return None
