# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"tracker": "torch_ember_core.ipynb",
         "emberTracker": "torch_ember_core.ipynb",
         "moduleTrack": "torch_ember_core.ipynb",
         "get_stats": "torch_ember_core.ipynb",
         "torchEmber": "torch_ember_core.ipynb",
         "check_existance": "utils.ipynb",
         "HOME": "utils.ipynb",
         "EMBER": "utils.ipynb",
         "DATA": "utils.ipynb",
         "LOG": "utils.ipynb",
         "get_ember_list": "utils.ipynb",
         "unpack_meta": "utils.ipynb",
         "get_ember_df": "utils.ipynb",
         "emberReader": "utils.ipynb"}

modules = ["core.py",
           "utils.py"]

doc_url = "https://raynardj.github.io/torchember/"

git_url = "https://github.com/raynardj/torchember/tree/master/"

def custom_doc_links(name): return None
