# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"color": "helper.ipynb",
         "tint": "helper.ipynb",
         "tracker": "helper.ipynb",
         "emberTracker": "helper.ipynb",
         "moduleTrack": "torch_ember_core.ipynb",
         "get_stats": "torch_ember_core.ipynb",
         "torchEmber": "torch_ember_core.ipynb",
         "check_existance": "utils.ipynb",
         "HOME": "utils.ipynb",
         "EMBER": "utils.ipynb",
         "DATA": "utils.ipynb",
         "LOG": "utils.ipynb",
         "get_ember_list": "utils.ipynb",
         "unpack_meta": "utils.ipynb",
         "get_ember_df": "utils.ipynb",
         "get_ember_record": "utils.ipynb",
         "emberReader": "utils.ipynb",
         "md5hash": "why_hat.ipynb",
         "RichColumn": "why_hat.ipynb",
         "RichDF": "why_hat.ipynb"}

modules = ["helper.py",
           "core.py",
           "utils.py",
           "whyhat.py"]

doc_url = "https://raynardj.github.io/torchember/"

git_url = "https://github.com/raynardj/torchember/tree/master/"

def custom_doc_links(name): return None
