# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/50_extension_fastai.ipynb (unless otherwise specified).

__all__ = ['EmberCallback']

# Cell
from .core import torchEmber
from fastai.basic_train import Learner,LearnerCallback

# Cell
class EmberCallback(LearnerCallback):
    """
    A call back for fastai learner
    """
    def __init__(self,learn:Learner, te:torchEmber):
        super().__init__(learn)
        self.te = te

    def on_step_end(self,**kwargs):
        self.te.log_model()