# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/why_hat.ipynb (unless otherwise specified).

__all__ = ['RichColumn', 'RichDF']

# Cell
import pandas as pd
import numpy as np
from pathlib import Path
import os
import json
from .core import color

# Cell
class RichColumn(object):
    """
    A pandas series manager
    """
    def __init__(self,column,min_occur = 5):
        self.col = column
        self.col.rc = self
        self.name = self.col.name
        self.min_occur = min_occur
        self.use = True
        self.is_conti = True
        self.defined = False

    def kill(self):
        self.defined = True
        self.use = False

    def conti(self):
        self.defined = True
        self.is_conti = True

    def disc(self):
        self.defined = True
        self.is_conti = False

    def is_number(self):
        return self.col.dtype in (int,float,
                              np.float16,np.float32,np.float64,np.float64,
                              np.int0,np.int8,np.int16,np.int32,np.int64)

    def __bool__(self):
        return self.use

    def __len__(self):
        if self.is_conti:
            return 1
        else:
            width = len(self.top_freq)
            width =1 if width==2 else width
            return width

    def __repr__(self,):
        return f"<Rich Column:{self.name}>"

    def top_freq_(self):
        freq = self.freq()
        self.top_freq = freq[freq[self.name]>=self.min_occur].reset_index()
        return self.top_freq

    def freq(self):
        return pd.DataFrame(data=self.col.value_counts())

class RichDF(object):
    """
    A pandas dataframe manager
    """
    def __init__(self,df):
        self.df = df
        self.columns = dict()
        for colname in self.df:
            self.columns.update({colname:RichColumn(df[colname])})

    @property
    def col_conf(self):
        return dict((k,{"use":v.use,"is_cont":v.is_conti}) for k,v in self.columns.items())

    def kill(self,colname):
        self.df[colname].rc.kill()

    def conti(self,colname):
        self.df[colname].rc.conti()

    def disc(self,colname):
        self.df[colname].rc.disc()

    def set_col(self,rcol):
        if rcol.defined:
            print(f"{rcol.name} defined, use:{rcol.use}, contineus?:{rcol.is_conti}")
        print(color.bold("="*30))
        print(color.cyan(rcol.name))
        print(color.red(f"number? {rcol.is_number()}"))
        print(rcol.top_freq_().head(5))

        print(color.red("Is this a [C]ontineous, [D]iscrete or a column we do[N]'t need? default N"))
        x = input().lower()
        if x=="c":
            rcol.conti()

        elif x =="d":
            rcol.disc()

        elif x =="":
            rcol.kill()

        elif x=="n":
            rcol.kill()

        else:
            print(color.yellow(f"{x} not found Again?"))


    def tour(self):
        for colname in self.df:
            col = self.df[colname]
            while col.rc.defined==False:
                self.set_col(col.rc)

